services:
    backend:
        build: backend
        ports:
            - 5000:5000
        volumes:
            - ./backend:/app:ro
        links:
            - mongo:mongo
        environment:
            PORT: 5000
    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db:rw
