services:
    backend:
        container_name: deepseek-backend
        build:
            context: backend
            dockerfile: Dockerfile.dev
        restart: on-failure
        volumes:
            - ./backend:/app
            - ./data/uploads:/uploads:rw
        links:
            - mongo:mongo
        ports:
            - 5000:5000
        environment:
            FLASK_RUN_PORT: 5000
            FRONTEND_URL: 'http://localhost:4000'
            UPLOADS_FOLDER: '/uploads'
    frontend:
        container_name: deepseek-frontend
        build:
            context: frontend
            dockerfile: Dockerfile.dev
        restart: on-failure
        volumes:
            - ./frontend:/app:delegated
            - ./frontend/package.json:/app/package.json
            - ./frontend/package-lock.json:/app/package-lock.json
            - notused:/app/node_modules
        ports:
            - 4000:4000
        environment:
            PORT: 4000
            VITE_API_URL: 'http://localhost:5000'
    mongo:
        container_name: deepseek-mongo
        image: mongo
        restart: on-failure
        ports:
            - 27017:27017
        volumes:
            - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./data/db:/data/db:rw
volumes:
    notused: