services:
    backend:
        container_name: deepseek-backend
        build:
            context: backend
            dockerfile: Dockerfile.prod
        restart: on-failure
        links:
            - mongo:mongo
        ports:
            - 5000:5000
        environment:
            FLASK_RUN_PORT: 5000
            FRONTEND_URL: 'https://capstone.ian-turner.xyz'
            BACKEND_URL: 'https://api.capstone.ian-turner.xyz'
            UPLOADS_FOLDER: '/uploads'
        volumes:
            - ./data/uploads:/uploads:rw
    frontend:
        container_name: deepseek-frontend
        build:
            context: frontend
            dockerfile: Dockerfile.prod
        restart: on-failure
        ports:
            - 4000:80
    mongo:
        container_name: deepseek-mongo
        image: mongo
        restart: on-failure
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db:rw
            - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
