# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegister():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_register(self):
    self.vars["ran"] = self.driver.execute_script("return Math.random()")
    self.driver.get("http://localhost:4000/")
    self.driver.set_window_size(550, 691)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(1) > .w-100").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(1) > .w-100").send_keys(self.vars["ran"]@email.com)
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(2) > .w-100").send_keys(self.vars["ran"])
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(3) > .w-100").send_keys("tester")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".mr-3 > svg")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".mr-3 > svg")
    assert len(elements) > 0
    self.driver.close()
  
