# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegisterlogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registerlogin(self):
    self.driver.get("http://localhost:4000/")
    self.driver.set_window_size(1000, 1000)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
    self.vars["random"] = self.driver.execute_script("return Math.random()")
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(1) > .w-100").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(1) > .w-100").send_keys(f"{self.vars['random']}@email.com")
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(2) > .w-100").send_keys(str(self.vars["random"]))
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(3) > .w-100").send_keys("register")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".mr-3 > svg")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".mr-3 > svg")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".mr-3 > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-2:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".btn")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".btn")
    assert len(elements) > 0
    
    # Click login button first
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    
    # Enter username
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(1) > .w-100").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(1) > .w-100").send_keys(self.vars["random"])
    
    # Enter wrong password
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(2) > .w-100").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(2) > .w-100").send_keys("wrongpassword")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    
    # Verify error message
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".p-3 > p")))
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".p-3 > p")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".p-3 > p").text == "Invalid password"
    
    # Clear and enter correct password
    password_field = self.driver.find_element(By.CSS_SELECTOR, ".mb-2:nth-child(2) > .w-100")
    password_field.clear()
    password_field.send_keys("register")
    
    # Click the login button
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    
    # Wait for successful login (profile icon)
    WebDriverWait(self.driver, 30).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".mr-3 > svg")))
    
    # Optional: Verify successful login
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".mr-3 > svg")
    assert len(elements) > 0
    
    self.driver.close()
  
